# Generated by Django 4.0.2 on 2022-02-27 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.category')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video1', models.URLField()),
                ('video2', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TextTutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(to='exercise.Category')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.muscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_tutorial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercise.videotutorials'),
        ),
    ]
