# Generated by Django 4.0.2 on 2022-02-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_remove_muscle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='category',
            field=models.ManyToManyField(to='exercise.Category'),
        ),
        migrations.AddField(
            model_name='muscle',
            name='type_of_muscle',
            field=models.CharField(default=None, max_length=75),
            preserve_default=False,
        ),
    ]
