# Generated by Django 4.0.2 on 2022-02-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exercise_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='gender',
        ),
    ]
