# Generated by Django 4.0.2 on 2022-02-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_remove_exercise_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gender',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
